config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  
  
  get 'welcome/index'
  
  authenticated :user do
    root "todo_lists#index", as: "authenticated_root"
  end
  
  root "welcome#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :todo_lists
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  
  def completed?
    !completed_at.blank?
  end
  
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todo_lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]
  
  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    
    redirect_to @todo_list
  end
  
  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Failed to create todo list item."
    end
    redirect_to @todo_list
  end
  
  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Todo Item Completed!"
  end
  
  private
  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
  
  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end
  
  def todo_item_params
    params[:todo_item].permit(:content)
  end
  
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.build
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:category_id, :title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>2-Do | A better todo list.</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "2-Do", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Dashboard", root_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <%= yield %>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
<%= f.text_field :content, placeholder: "New Todo Item" %>
  <%= f.submit label: "Create Todo Item", class: "todo_item_btn"%>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix" style="margin-right: 0px;margin-left: 0px;">
  <% if todo_item.completed? %>
    <div class="complete">
      <%= link_to  complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
  </div>
  <div class="todo_item">
    <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
  </div>
  <div class="trash">
    <%= link_to  todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
    <i class="fa fa-trash"></i>
    <% end %>
  </div>
  <% else %>
    <div class="complete">
      <%= link_to  complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
        <i class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p><%= todo_item.content %></p>
    </div>
    <div class="trash">
     <%= link_to  todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
      <i class="fa fa-trash"></i>
     <% end %>
    </div>
  <% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"} %>
  </div>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions" style="text-align:center;">
    <%= f.submit label: "Create Todo List", class: "todo_item_btn" %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="container">
  <h1 class="todo_list_title">UpdateTodo List</h1>

  <div class="forms">
    <%= render 'form' %>
  </div>

  <div class="links">
    <%= link_to  @todo_list do %>
      <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>

    <%= link_to  todo_lists_path  do %> 
      <i class="fa fa-home" style="margin-left: 10px; font-size: 25px;"></i>
    <% end %>
  </div>
</div>
<br>

app/views/todo_lists/index.html.erb
<div class="col-md-12">  
  <div class="newlistcontainer">
    <div class="links">
      <%= link_to "New Todo List", new_todo_list_path, class: "todo_list_title", style: "font-size: 1.75em;" %>
    </div>
    <p class="notice" id="notice"><%= notice %></p>
    <p class="alert" id="notice"><%= alert %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="indexcontainer">
      <h1 class="todo_list_title" style="font-size:2.em;">Important - Due Soon</h1>
      <hr>
      <% @todo_lists.each do |todo_list| %>
        <% if user_signed_in? && todo_list.user_id === current_user.id %>
          <% if todo_list.category_id === 1 %>
            <div class="index-row clearfix">
              <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
              <p class="todo_list_sub_title"><%= todo_list.description %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="indexcontainer">
      <h1 class="todo_list_title" style="font-size:2.em;">Not Important - Due Soon</h1>
      <hr>
      <% @todo_lists.each do |todo_list| %>
        <% if user_signed_in? && todo_list.user_id === current_user.id %>
          <% if todo_list.category_id === 2 %>
            <div class="index-row clearfix">
              <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
              <p class="todo_list_sub_title"><%= todo_list.description %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="indexcontainer">
      <h1 class="todo_list_title" style="font-size:2.em;">Important - Due Later</h1>
      <hr>
      <% @todo_lists.each do |todo_list| %>
        <% if user_signed_in? && todo_list.user_id === current_user.id %>
          <% if todo_list.category_id === 3 %>
            <div class="index-row clearfix">
              <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
              <p class="todo_list_sub_title"><%= todo_list.description %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="indexcontainer">
      <h1 class="todo_list_title" style="font-size:2.em;">Not Important - Due Later</h1>
      <hr>
      <% @todo_lists.each do |todo_list| %>
        <% if user_signed_in? && todo_list.user_id === current_user.id %>
          <% if todo_list.category_id === 4 %>
            <div class="index-row clearfix">
              <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
              <p class="todo_list_sub_title"><%= todo_list.description %></p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/todo_lists/new.html.erb
<div class="container">
  <h1 class="todo_list_title">New Todo List</h1>

  <div class="forms">
    <%= render 'form' %>
  </div>

  <div class="links">
    <%= link_to  todo_lists_path do%>
      <i class="fa fa-arrow-left" style="font-size:24px;"></i>
    <% end %>
  </div>
</div>
<br>

app/views/todo_lists/show.html.erb
<div class="container">
  <p class="notice" id="notice"><%= notice %></p>
  <p class="alert" id="notice"><%= alert %></p>
  <h2 class="todo_list_title"><%= @todo_list.title%></h2>
  <p class="todo_list_sub_title"><%= @todo_list.category.name%></p>
  <p class="todo_list_sub_title"><%= @todo_list.description %></p>

  <div id="todo_items_wrapper">
    <%= render @todo_list.todo_items %>
    <div id="form">
      <%= render "todo_items/form" %>
      <br>
    </div>
  </div>

  <div class="todoshowbuttons" style="text-align:center;">
     <%= link_to  todo_lists_path do %>
      <i class="fa fa-arrow-left" style="font-size:24px;"></i>
    <% end %>

    <%= link_to edit_todo_list_path(@todo_list) do %>
      <i class="fa fa-pencil-square-o" style="margin-left: 10px; font-size:24px;"></i>
    <% end %>

    <%= link_to  todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fa fa-trash" style="margin-left: 10px; font-size:24px;"></i>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
  <div id="banner">
    <div class="banner_content">
      <h1 style="color: #1F7972;">2-Do</h1>
      <p>A better way to keep track of the things you need 2-Do.</p>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %>
    </div>
  </div>






<div id="callouts">
    <div class="callout_inner">
      <h2>The Convoy Time Management Matrix</h2>
      <br>
      <div class="wrapper">
        <p style="padding-left: 15%; padding-right: 15%;">Being able to prioritize what it is you need to do is crucial in order to stay truly productive.This is where Convoy's Time Management Matrix comes in. Using 2-Do will allow you to stay productive by prioritizing your todo lists based on importance and urgency. The matrix is broken down into 4 quadrants. 1. Important - Due Soon, 2. Not Important - Due Soon, 3. Important -Due Later, 4. Not Important - Due Later. The secret to using this matrix to increase your productivity is to always do the Important - Due Soon & Important - Due Later quandrants first and sometimes you might need to say, "This thing that is due soon but is not important, I just wont do it. Its not important, it says so on the chart!" - Randy Pausch. And by doing this you will mysteriously have time to work on the things that are important but not due soon so that next week, those things you had to do never had a chance of being in the first quadrant because you killed it in the crib.</p>
      </div>
    </div>
  </div>




<div id="messhall">
    <div class="callout_inner">
      
      
      
      <div class="callout">
          <i class="fa fa-check fa-3x"></i>
          <p>Easily create and manage your todo lists from any device, any where. Thanks to our responive design you can always have your 2-Do List with you on your phone, tablet and desktop.</p> 
        </div>

        <div class="callout">
           <i class="fa fa-sort fa-3x"></i>
           <p >Easily sort all of your 2-Do lists based on importance and urgency so you always know what really needs to get done in which order!</p>
        </div>

        <div class="callout">
          <i class="fa fa-exchange fa-3x"></i>
         <p>Thanks to our user-freindly design, it is extremely easy for users to move their to-do lists from quadrant to quadrant allowing you to easily stay on top of things as they become less or more important or urgent.</p> 
        </div>
      
    </div>
  </div>


  <div id="bottom_cta">
    <div class="wrapper">
      <h3>Don't Fall Victim to the Time Famine!</h3>
      <h2>Sign Up Today!</h2>
      <br>
      <p style="padding-left: 15%; padding-right: 15%;">Stop feeling like there is never enough time to do all the things you find important. Start keeping a better 2-Do list organizaed by importance and urgency so you can forever escape the Time Famine!</p>
      <%= link_to "Start Today!", new_user_registration_path, class: "btn btn-default" %>
    </div>
  </div>
  <br>
  <footer style="text-align:center; color:white;">&copy; 2-Do | Dedicated to Randy Pausch</footer>
<br>